version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "11130:11130"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:11130
      - ConnectionStrings__DefaultConnection=server=db;port=3306;database=ziraatdb;user=root;password=0000;
    networks:
      - app-network

  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8081:80"
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: ziraatdb
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # Ana makinedeki kube config'i Jenkins home altına mount ediyoruz
      - ${HOME}/.kube:/var/jenkins_home/.kube:ro
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

volumes:
  db-data:
  jenkins-data:

networks:
  app-network:
