# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 11130
      targetPort: 11130
      nodePort: 30082
  type: NodePort
